let grp = [
  {
    name: "String Reverse",
    accp: "78",
    diif: "Easy",
    con:"String",
    lvl:"Basic",
  },
  {
    name: "Palindrome",
    accp: "80",
    diif: "Easy",
    con:"Loops",
    lvl:"Intermediate",
  },
  {
    name: "Max Element",
    accp: "84",
    diif: "Hard",
    con:"Array",
    lvl:"Advanced",
  },
  {
    name: "Min Element",
    accp: "68",
    diif: "Medium",
    con:"Array",
    lvl:"Advanced",
  },
  {
    name: "Find ELement",
    accp: "89",
    diif: "Hard",
    con:"Array",
    lvl:"Intermediate",
  },
  {
    name: "Sum OF Array",
    accp: "98",
    diif: "Easy",
    con:"Array",
    lvl:"Basic",
  },
  {
    name: "Hello WOrld",
    accp: "100",
    diif: "Easy",
    con:"String",
    lvl:"Basic",
  },
  {
    name: "Sum Of Two Integers",
    accp: "100",
    diif: "Easy",
    con:"Integer",
    lvl:"Basic",
  },
  {
    name: "String Reverse",
    accp: "78",
    diif: "Easy",
    con:"String",
    lvl:"Basic",
  },
  {
    name: "Palindrome",
    accp: "80",
    diif: "Easy",
    con:"Loops",
    lvl:"Intermediate",
  },
  {
    name: "Max Element",
    accp: "84",
    diif: "Hard",
    con:"Array",
    lvl:"Advanced",
  },
  {
    name: "Min Element",
    accp: "68",
    diif: "Medium",
    con:"Array",
    lvl:"Advanced",
  },
  {
    name: "Find ELement",
    accp: "89",
    diif: "Hard",
    con:"Array",
    lvl:"Intermediate",
  },
  {
    name: "Sum OF Array",
    accp: "98",
    diif: "Easy",
    con:"Array",
    lvl:"Basic",
  },
  {
    name: "Hello WOrld",
    accp: "100",
    diif: "Easy",
    con:"String",
    lvl:"Basic",
  },
  {
    name: "Sum Of Two Integers",
    accp: "100",
    diif: "Easy",
    con:"Integer",
    lvl:"Basic",
  },
];
export default grp;
